# Generated by Django 3.2.5 on 2021-07-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bassin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='bassin')),
            ],
            options={
                'verbose_name': 'Bassin',
            },
        ),
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='dep')),
            ],
            options={
                'verbose_name': 'Département',
            },
        ),
        migrations.CreateModel(
            name='Drv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='drv')),
            ],
            options={
                'verbose_name': 'Direction Régionale des Ventes',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='ville')),
            ],
            options={
                'verbose_name': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='agent')),
                ('drv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visio.drv')),
            ],
            options={
                'verbose_name': 'Agent',
            },
        ),
    ]
