# Generated by Django 3.2.5 on 2021-07-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='agent')),
            ],
            options={
                'verbose_name': 'Agent',
            },
        ),
        migrations.CreateModel(
            name='Bassin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='bassin')),
            ],
            options={
                'verbose_name': 'Bassin',
            },
        ),
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='dep')),
            ],
            options={
                'verbose_name': 'Département',
            },
        ),
        migrations.CreateModel(
            name='Drv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='drv')),
            ],
            options={
                'verbose_name': 'Direction Régionale des Ventes',
            },
        ),
        migrations.CreateModel(
            name='SegmentCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='segment_commercial')),
            ],
            options={
                'verbose_name': 'Segment Commercial',
            },
        ),
        migrations.CreateModel(
            name='SegmentMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='segment_marketing')),
            ],
            options={
                'verbose_name': 'Segment Marketing',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='ville')),
            ],
            options={
                'verbose_name': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='Pdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.agent')),
                ('bassin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.bassin')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.dep')),
                ('drv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.drv')),
                ('segment_commercial', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='visio.segmentcommercial')),
                ('segment_marketing', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='visio.segmentmarketing')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.ville')),
            ],
            options={
                'verbose_name': 'Point de Vente',
            },
        ),
        migrations.CreateModel(
            name='AgentFinitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='agent_finitions')),
                ('drv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.drv')),
            ],
            options={
                'verbose_name': 'Agent Finitions',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='drv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.drv'),
        ),
    ]
