# Generated by Django 3.2.5 on 2021-07-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='longitude'),
        ),
    ]
