# Generated by Django 3.2.5 on 2021-07-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='segment_commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.segmentcommercial'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='segment_marketing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.segmentmarketing'),
        ),
    ]
