# Generated by Django 3.2.5 on 2021-07-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0003_auto_20210715_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='name',
            field=models.CharField(default='Inconnu', max_length=64, verbose_name='name'),
        ),
    ]
