# Generated by Django 3.2.5 on 2021-07-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0004_alter_pdv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='code',
            field=models.CharField(default='Inconnu', max_length=10, verbose_name='code'),
        ),
    ]
