# Generated by Django 3.2.5 on 2021-07-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0005_alter_pdv_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='ensemble',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visio.ensemble'),
        ),
    ]
