# Generated by Django 3.2.5 on 2021-07-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0006_pdv_ensemble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigne',
            name='name',
            field=models.CharField(default='Inconnu', max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='SousEnsemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=64, unique=True, verbose_name='name')),
                ('ensemble', models.ForeignKey(default=43, on_delete=django.db.models.deletion.PROTECT, to='visio.ensemble')),
            ],
            options={
                'verbose_name': 'Sous-Ensemble',
            },
        ),
    ]
