# Generated by Django 3.2.5 on 2021-07-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0007_auto_20210715_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='sous_ensemble',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visio.sousensemble'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='enseigne',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='visio.enseigne'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='ensemble',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.PROTECT, to='visio.ensemble'),
        ),
    ]
