# Generated by Django 3.2.5 on 2021-07-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0008_auto_20210715_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sousensemble',
            name='ensemble',
        ),
    ]
