# Generated by Django 3.2.5 on 2021-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0010_auto_20210716_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdv',
            name='redistributed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdv',
            name='redistributedEnduit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdv',
            name='sale',
            field=models.BooleanField(default=True),
        ),
    ]
