# Generated by Django 3.2.5 on 2021-07-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0011_auto_20210716_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='closedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date de clôture'),
        ),
        migrations.AddField(
            model_name='pdv',
            name='pointFeu',
            field=models.BooleanField(default=False),
        ),
    ]
