# Generated by Django 3.2.5 on 2021-07-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0012_auto_20210716_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drv',
            options={'verbose_name': 'DRV'},
        ),
        migrations.AlterModelOptions(
            name='enseigne',
            options={'verbose_name': 'Enseigne'},
        ),
        migrations.AlterField(
            model_name='pdv',
            name='closedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date de Fermeture'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='code',
            field=models.CharField(default='Inconnu', max_length=10, verbose_name='PDV code'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='name',
            field=models.CharField(default='Inconnu', max_length=64, verbose_name='PDV'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='pointFeu',
            field=models.BooleanField(default=False, verbose_name='Point Feu'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='redistributed',
            field=models.BooleanField(default=True, verbose_name='Redistribué'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='redistributedEnduit',
            field=models.BooleanField(default=True, verbose_name='redistribué Enduit'),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='sale',
            field=models.BooleanField(default=True, verbose_name='Ne vend pas de plaque'),
        ),
    ]
