# Generated by Django 3.2.5 on 2021-07-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0013_auto_20210719_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=32, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Industrie',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=32, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
    ]
