# Generated by Django 3.2.5 on 2021-07-19 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0014_industrie_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date de Saisie')),
                ('volume', models.FloatField(blank=True, default=0.0, verbose_name='Volume')),
                ('industry', models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, to='visio.industrie')),
                ('pdv', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visio.pdv')),
                ('product', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='visio.produit')),
            ],
            options={
                'verbose_name': 'Ventes',
            },
        ),
    ]
